# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run-test:
    runs-on: ubuntu-latest
    container: perl:latest
    steps:
      - uses: actions/checkout@v2
      - name: run a simple unit test
        run: |
          prove -Ilib -v t/*.t
  build-project:
    runs-on: ubuntu-latest
    container: eltenedor/coverage-perl:latest
    steps:
      - uses: actions/checkout@v2
      - name: Build project, run tests and coverage analysis
        run: |
          perl -Ilib Build.PL 
          ./Build build
          cover -test
          ./Build testcover
#       env:
#         CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
 
      - uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: cover_db/
      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: cover_db/coverage.html # optional
          flags: unittests # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)

  cover-codecov:
    runs-on: ubuntu-latest
    container: eltenedor/coverage-perl:latest
    steps:
      - uses: actions/checkout@v2
      - name: Build project, run tests and coverage analysis
        run: |
          perl -Ilib Build.PL 
          ./Build build
          cover -test -report codecov
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
