name: Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    container: eltenedor/coverage-perl:latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests and push coverage analysis
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          perl Build.PL 
          cover -test
          cover -report codecov
